### PR TITLE
Upgraded to ES6 and added tests for instance of coinpayments error.

### LINKED ISSUE #63: Instance of CoinpaymentsError is not CoinpaymentsError
A variable that is instantiated with `CoinpaymentsError` is not an instance of `CoinpaymentsError`.

Here's a basic example:
```ts
import CoinpaymentsError from "coinpayments/dist/error";

const error = new CoinpaymentsError();

assert(error instanceof CoinpaymentsError);
```

I'm guessing it's because tsconfig target is `ES5`.
Would it be possible to change this to `ES6` ?

### PR DESCRIPTION
**Pull request by Ranguna**
Fixed #63

### CODE REVIEW

**Comment by Ranguna** [comment]
@OrahKokos let me know if we should go ahead with this and if the major version should be bumped.
Thanks!

**Comment by OrahKokos** [comment]
On hold for now. Need to revisit all of the ```instanceof``` things

**Comment by OrahKokos** [comment]
@Ranguna So why target ES6 for typescript? 
ES5 should be compatible with everything no?

**Comment by Ranguna** [comment]
@OrahKokos apparently es5 doesn't have "real" class support. 
Typescript emulates classes by using functions and prototype inheritance (which is the same, even for "real" classes iirc) , but instanceof doesn't work.

Give it a try, change this PR to ES5 and run the tests, that new one should fail.

**Comment by OrahKokos** [comment]
Thanks for the answer. Interesting... odd.
Will investigate this over the weekend, if it turns out its a breaking change and we have to go to 3.0.0.... then that might entail some more features (headless).
Sorry for the delay, was moving countries :D

**Comment by Ranguna** [comment]
No worries man, good luck with the moving and take your time!

To improve error handling even more, I was thinking about talking with coinpayments to see if they could provide some error codes instead of just sending text, but that's an idea for the future 👌

**Comment by OrahKokos** [comment]
@Ranguna Was intending to do the same, so we dont have to guess. Please post if you get anything into the discussion so we map shit out. Thanks a lot

**Comment by Ranguna** [comment]
Yeah dude no worries, will send out an email sometime this weekend and post here any updated.

**Comment by OrahKokos** [comment]
@Ranguna Hey bro. 
Did some digging, it is a known issue: https://stackoverflow.com/questions/47941324/inherited-exceptions-and-instanceof
There is a solution we can use without doing target ES6, which would  be a breaking change.

This is pretty much a bug now, worth only of a minor version tick. We can separate error types from error fixes. My suggestion is to close this PR, tomorrow I can publish 2.1.3 and instanceof will work.
All good?

**Comment by Ranguna** [comment]
Wow did not expect that one. All right sound good to me man 👌
Closing.

**Pull request closed without merging**
